spring.application.name=Thinkitive_Demo_Project
spring.datasource.url= jdbc:postgresql://localhost:5432/ThinkitveDemoProject
spring.datasource.username=postgres
spring.datasource.password=1234
server.port=8000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
jwt.secret=mySecretKeyForThinkitiveProjectJwtAuthentication123456
jwt.expiration=1800000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/thinkitive
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=thinkitive
keycloak.admin.client-id=thinkitive-admin
keycloak.admin.client-secret=JTxxlaubTpgue1kk8TzahvxBauzxO5mCohGBtwNIXmoW46PM0mmEghslK6qpUBLS4VrkT8PF3PMfVcFF7olu33